name: MobCustom
version: '${project.version}'
main: com.thebidouille_mob_custom.CustomMobLoader
api-version: '1.21'
commands:
  spawncompanion:
    description: Fait apparaître un compagnon personnalisé
    usage: /spawncompanion <mobId>
    permission: custommob.spawn